# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: update cache
  apt:
    update_cache: yes

- name: install aptitude
  apt:
    name: aptitude

- name: remove packages
  apt:
    name: "{{ software_packages_to_remove }}"
    state: absent
    purge: yes

- name: autoremove
  apt:
    autoremove: yes
    purge: yes

- name: install packages
  apt:
    name: "{{ software_packages_to_install }}"

- name: full-upgrade
  apt:
    upgrade: full
  when: software_packages_full_upgrade

- name: autoremove
  apt:
    autoremove: yes
    purge: yes

- name: list packages in "rc" state
  shell: "dpkg -l | grep ^rc | awk '{print $2}'"
  changed_when: false
  failed_when: false
  register: rc_packages

- name: purge packages in "rc" state
  apt:
    name: "{{ rc_packages.stdout_lines }}"
    state: absent
    purge: yes
  when: rc_packages.rc == 0 and rc_packages.stdout != ''
