# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- set_fact:
    is_client: no
    is_controller: no
    is_compute: no
    partitions: []

- set_fact: is_controller=yes
  when: "'slurm_controller' in group_names"

- set_fact: is_compute=yes
  when: "'slurm_compute' in group_names"

- set_fact: is_client=yes
  when: "'slurm_client' in group_names"

- name: ubuntu vars
  include_vars:
    file: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: always

- name: ubuntu tasks
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: common tasks
  include_tasks: common.yml

- name: controller tasks
  include_tasks: controller.yml
  when: is_controller

- name: compute tasks
  include_tasks: compute.yml
  when: is_compute

- name: pyxis tasks
  include_tasks: pyxis.yml
  when: (is_controller or is_compute) and slurm_install_pyxis
  tags: pyxis
