# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: add key
  apt_key:
    url: "{{ mofed_repo_gpg_url }}"
    state: present

- name: add repo
  get_url:
    url: "{{ mofed_repo_base_url }}/{{ mofed_package_version }}/{{ _ubuntu_repo_dist_name }}/{{ _ubuntu_repo_file_name }}"
    dest: "{{ _ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root

- name: install packages
  apt:
    name:
      - libc6-dev # XXX DKMS will fail without this
      - mlnx-ofed-kernel-dkms
      - mlnx-ofed-kernel-utils
      - rdma-core
      - ibverbs-utils
      - ibverbs-providers
    state: "{{ mofed_package_state }}"
    update_cache: yes
